name: xpkg
description: Build and publish Crossplane packages.
inputs:
  command:
    description: kubectl crossplane command
    required: true
runs:
  using: composite
  steps: 
    - run: curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh
      shell: bash
    - run: "./kubectl-crossplane ${{ inputs.command }}"
      shell: bash
