name: xpkg
description: Build and publish Crossplane packages.
inputs:
  command:
    description: kubectl crossplane command
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}
