name: xpkg
description: Build and publish Crossplane packages.
inputs:
  channel:
    description: release channel
    required: true
    default: stable
  version:
    description: release version
    required: true
    default: current
  command:
    description: kubectl crossplane command
    required: true
runs:
  using: composite
  steps: 
    - run: "[ -f crossplane ] || curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh"
      shell: bash
      env:
        XP_CHANNEL: ${{ inputs.channel }}
        XP_VERSION: ${{ inputs.version }}
    - run: "./crossplane ${{ inputs.command }}"
      shell: bash
