name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

env:
  DOCKER_USR: ${{ secrets.DOCKER_USR }}

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to Docker
        uses: docker/login-action@v1
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}
      - name: Build xpkg
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: build
          type: configuration
          path: /github/workspace/test/xpkg-action-test
          destination: --name=xpkg-action-test
      - name: Push xpkg
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: push
          type: configuration
          path: /github/workspace/test/xpkg-action-test/xpkg-action-test.xpkg
          destination: registry.upbound.io/crossplane-test/xpkg-action-test:v0.0.1
