name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      channel:
        description: release channel
        required: true
        default: stable
      version:
        description: release version
        required: true
        default: current

env:
  DOCKER_USR: ${{ secrets.DOCKER_USR }}

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to Docker
        uses: docker/login-action@v1
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}
      - name: Build xpkg
        uses: crossplane-contrib/xpkg-action@master
        with:
          channel: ${{ github.event.inputs.channel }}
          version: ${{ github.event.inputs.channel }}
          command: build configuration -f test/xpkg-action-test --name=xpkg-action-test
      - name: Push xpkg
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: push configuration -f test/xpkg-action-test/xpkg-action-test.xpkg registry.upbound.io/crossplane-test/xpkg-action-test:v0.0.1
